name: hubs_data
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/samlet/hubs_data

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  crypto: ^3.0.0
  http: ^0.13.1
  json_annotation: ^4.5.0
  meta: ^1.1.7
  logging: ^1.0.1
  dio: ^4.0.0

dev_dependencies:
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  test: ^1.3.0
  mocktail: ^0.3.0
  lints: ^2.0.0
